name: Build and deploy Node.js app to Azure Web App - stork watch

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Zip all files for upload between jobs
        # IMPORTANT: .next is a hidden folder and will NOT be included in the zip unless we specify it
        # To fix: /home/site/wwwroot/node_modules/.bin/next: 1: ../next/dist/bin/next: not found
        run: zip next.zip ./* .next -qr

      - name: "Deploy to Azure Web App"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "stork-watch"
          slot-name: "dev"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_BF2FAE33C09E459280ECE1DFC80E8304 }}
          package: next.zip
